/**
 * storyboard proxy — Generate Caddyfile from ports.json and start/reload Caddy.
 *
 * Caddy listens on port 80 for storyboard.localhost, routing:
 *   /storyboard/*              → main (port 1234)
 *   /<branchname>/storyboard/* → worktree (assigned port)
 *
 * Requires Caddy to be installed (brew install caddy).
 * Port 80 requires `sudo caddy start` — handled by `storyboard setup`.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { execSync } from 'child_process'
import { dirname } from 'path'
import { portsFilePath } from '../worktree/port.js'

const DOMAIN = 'storyboard.localhost'

export function generateCaddyfile(portOverrides = {}) {
  const portsFile = portsFilePath()
  const dir = dirname(portsFile)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })

  let ports = { main: 1234 }
  if (existsSync(portsFile)) {
    try {
      ports = JSON.parse(readFileSync(portsFile, 'utf8'))
    } catch {
      // Corrupted — use defaults
    }
  }

  // Apply runtime overrides (e.g. when assigned port was in use)
  Object.assign(ports, portOverrides)

  const mainPort = ports.main || 1234
  const branches = Object.entries(ports).filter(([name]) => name !== 'main')

  // Build Caddy route blocks — branches first (more specific), main last (fallback)
  const branchBlocks = branches
    .map(([name, port]) => `    # Worktree: ${name}\n    handle /${name}/* {\n        reverse_proxy localhost:${port}\n    }`)
    .join('\n\n')

  const caddyfile = `# Auto-generated by storyboard CLI — do not edit manually.
# Regenerated on every \`storyboard dev\` or \`storyboard proxy\`.

http://${DOMAIN} {
${branchBlocks ? branchBlocks + '\n\n' : ''}    # Main
    handle {
        reverse_proxy localhost:${mainPort}
    }
}
`

  const caddyfilePath = portsFile.replace('ports.json', 'Caddyfile')
  writeFileSync(caddyfilePath, caddyfile)
  return caddyfilePath
}

export function isCaddyInstalled() {
  try {
    execSync('caddy version', { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

export function isCaddyRunning() {
  try {
    // Caddy admin API on localhost:2019
    execSync('curl -sf http://localhost:2019/config/ >/dev/null 2>&1', { timeout: 2000 })
    return true
  } catch {
    return false
  }
}

export function reloadCaddy(caddyfilePath) {
  try {
    execSync(`caddy reload --config "${caddyfilePath}"`, { stdio: 'inherit', timeout: 5000 })
    return true
  } catch {
    return false
  }
}

export function startCaddy(caddyfilePath) {
  try {
    execSync(`sudo caddy start --config "${caddyfilePath}"`, { stdio: 'inherit' })
    return true
  } catch {
    return false
  }
}

// When run directly as `storyboard proxy` (not imported by setup.js)
const isDirectRun = process.argv[2] === 'proxy'
if (isDirectRun) {
  const caddyfilePath = generateCaddyfile()
  console.log(`[storyboard] Caddyfile written to ${caddyfilePath}`)

  if (!isCaddyInstalled()) {
    console.error('[storyboard] Caddy is not installed. Run: brew install caddy')
    process.exit(1)
  }

  if (isCaddyRunning()) {
    console.log('[storyboard] Reloading Caddy...')
    if (reloadCaddy(caddyfilePath)) {
      console.log(`[storyboard] Proxy ready at http://${DOMAIN}/`)
    } else {
      console.error('[storyboard] Failed to reload Caddy')
      process.exit(1)
    }
  } else {
    console.log('[storyboard] Starting Caddy (requires sudo for port 80)...')
    if (startCaddy(caddyfilePath)) {
      console.log(`[storyboard] Proxy ready at http://${DOMAIN}/`)
    } else {
      console.error('[storyboard] Failed to start Caddy')
      process.exit(1)
    }
  }
}
